name: Build and Export Docker Image

on:
  push:
    branches:
      - main  # 或者你想要触发构建的其他分支
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU (for multi-architecture support, optional)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        docker build --tag weaviate:latest .

    - name: Save Docker image as tar
      run: |
        mkdir -p ./image
        docker save -o ./image/weaviate.tar weaviate:latest

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image-tar
        path: ./image/weaviate.tar  
